/*
 * generated by Xtext 2.28.0
 */
package grid.gameoflife.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class GameOfLifeDSLProposalProvider extends AbstractGameOfLifeDSLProposalProvider {
}
