/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GameDSLIdeModule extends AbstractGameDSLIdeModule {
}
