grammar grid.gameoflife.GameOfLifeDSL with org.eclipse.xtext.common.Terminals

generate gameOfLifeDSL "http://www.gameoflife.grid/GameOfLifeDSL"


Grid: 'Grid:' name = ID
	  'length:' length = INT
	  'width:' width = INT
		(cells += Cell)*
;
Cell: 'row:' row = INT
	  'col:' col = INT
	  'state:' state = State
;
enum State:
	DEAD = 'dead' | 
	ALIVE = 'alive'
;

enum Operator:
	LT = '<' |
	EQ = '=' |
	GT = '>'
;