/*
 * generated by Xtext 2.28.0
 */
package grid.gameoflife.ui.tests;

import com.google.inject.Injector;
import grid.gameoflife.ui.internal.GameoflifeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameOfLifeDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameoflifeActivator.getInstance().getInjector("grid.gameoflife.GameOfLifeDSL");
	}

}
