/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameDSLScopeProvider extends DelegatingScopeProvider {
}
