/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GameDSLValidator extends AbstractGameDSLValidator {
}
