/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameDSLRuntimeModule extends AbstractGameDSLRuntimeModule {
}
