/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameDSLStandaloneSetup extends GameDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new GameDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
