/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.gameDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.grid.gameDSL.Cell#getRow <em>Row</em>}</li>
 *   <li>{@link gameoflife.grid.gameDSL.Cell#getCol <em>Col</em>}</li>
 *   <li>{@link gameoflife.grid.gameDSL.Cell#getNeighbours <em>Neighbours</em>}</li>
 *   <li>{@link gameoflife.grid.gameDSL.Cell#getState <em>State</em>}</li>
 * </ul>
 *
 * @see gameoflife.grid.gameDSL.GameDSLPackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' attribute.
   * @see #setRow(int)
   * @see gameoflife.grid.gameDSL.GameDSLPackage#getCell_Row()
   * @model
   * @generated
   */
  int getRow();

  /**
   * Sets the value of the '{@link gameoflife.grid.gameDSL.Cell#getRow <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' attribute.
   * @see #getRow()
   * @generated
   */
  void setRow(int value);

  /**
   * Returns the value of the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col</em>' attribute.
   * @see #setCol(int)
   * @see gameoflife.grid.gameDSL.GameDSLPackage#getCell_Col()
   * @model
   * @generated
   */
  int getCol();

  /**
   * Sets the value of the '{@link gameoflife.grid.gameDSL.Cell#getCol <em>Col</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col</em>' attribute.
   * @see #getCol()
   * @generated
   */
  void setCol(int value);

  /**
   * Returns the value of the '<em><b>Neighbours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neighbours</em>' attribute.
   * @see #setNeighbours(int)
   * @see gameoflife.grid.gameDSL.GameDSLPackage#getCell_Neighbours()
   * @model
   * @generated
   */
  int getNeighbours();

  /**
   * Sets the value of the '{@link gameoflife.grid.gameDSL.Cell#getNeighbours <em>Neighbours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neighbours</em>' attribute.
   * @see #getNeighbours()
   * @generated
   */
  void setNeighbours(int value);

  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * The literals are from the enumeration {@link gameoflife.grid.gameDSL.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see gameoflife.grid.gameDSL.State
   * @see #setState(State)
   * @see gameoflife.grid.gameDSL.GameDSLPackage#getCell_State()
   * @model
   * @generated
   */
  State getState();

  /**
   * Sets the value of the '{@link gameoflife.grid.gameDSL.Cell#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see gameoflife.grid.gameDSL.State
   * @see #getState()
   * @generated
   */
  void setState(State value);

} // Cell
