/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gameoflife.grid.ide.contentassist.antlr.internal.InternalGameDSLParser;
import gameoflife.grid.services.GameDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GameDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GameDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GameDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
			builder.put(grammarAccess.getGridAccess().getGroup(), "rule__Grid__Group__0");
			builder.put(grammarAccess.getCellAccess().getGroup(), "rule__Cell__Group__0");
			builder.put(grammarAccess.getGridAccess().getNameAssignment_1(), "rule__Grid__NameAssignment_1");
			builder.put(grammarAccess.getGridAccess().getCellsAssignment_2(), "rule__Grid__CellsAssignment_2");
			builder.put(grammarAccess.getCellAccess().getRowAssignment_1(), "rule__Cell__RowAssignment_1");
			builder.put(grammarAccess.getCellAccess().getColAssignment_3(), "rule__Cell__ColAssignment_3");
			builder.put(grammarAccess.getCellAccess().getNeighboursAssignment_5(), "rule__Cell__NeighboursAssignment_5");
			builder.put(grammarAccess.getCellAccess().getStateAssignment_6(), "rule__Cell__StateAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GameDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGameDSLParser createParser() {
		InternalGameDSLParser result = new InternalGameDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GameDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
