/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GameDSLStandaloneSetup extends GameDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GameDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
