/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class GameDSLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
