/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GameDSLUiModule extends AbstractGameDSLUiModule {
}
