/**
 * generated by Xtext 2.28.0
 */
package grid.gameoflife.gameOfLifeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see grid.gameoflife.gameOfLifeDSL.GameOfLifeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameOfLifeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameOfLifeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gameoflife.grid/GameOfLifeDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameOfLifeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameOfLifeDSLPackage eINSTANCE = grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link grid.gameoflife.gameOfLifeDSL.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see grid.gameoflife.gameOfLifeDSL.impl.GridImpl
   * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGrid()
   * @generated
   */
  int GRID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__NAME = 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__LENGTH = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__CELLS = 3;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link grid.gameoflife.gameOfLifeDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see grid.gameoflife.gameOfLifeDSL.impl.CellImpl
   * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 1;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__ROW = 0;

  /**
   * The feature id for the '<em><b>Col</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__COL = 1;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__STATE = 2;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link grid.gameoflife.gameOfLifeDSL.State <em>State</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see grid.gameoflife.gameOfLifeDSL.State
   * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getState()
   * @generated
   */
  int STATE = 2;

  /**
   * The meta object id for the '{@link grid.gameoflife.gameOfLifeDSL.Operator <em>Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see grid.gameoflife.gameOfLifeDSL.Operator
   * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 3;


  /**
   * Returns the meta object for class '{@link grid.gameoflife.gameOfLifeDSL.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Grid#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Grid#getName()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_Name();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Grid#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Grid#getLength()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_Length();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Grid#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Grid#getWidth()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_Width();

  /**
   * Returns the meta object for the containment reference list '{@link grid.gameoflife.gameOfLifeDSL.Grid#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Grid#getCells()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Cells();

  /**
   * Returns the meta object for class '{@link grid.gameoflife.gameOfLifeDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Cell#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Cell#getRow()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Row();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Cell#getCol <em>Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Cell#getCol()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Col();

  /**
   * Returns the meta object for the attribute '{@link grid.gameoflife.gameOfLifeDSL.Cell#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Cell#getState()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_State();

  /**
   * Returns the meta object for enum '{@link grid.gameoflife.gameOfLifeDSL.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>State</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.State
   * @generated
   */
  EEnum getState();

  /**
   * Returns the meta object for enum '{@link grid.gameoflife.gameOfLifeDSL.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operator</em>'.
   * @see grid.gameoflife.gameOfLifeDSL.Operator
   * @generated
   */
  EEnum getOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameOfLifeDSLFactory getGameOfLifeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link grid.gameoflife.gameOfLifeDSL.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see grid.gameoflife.gameOfLifeDSL.impl.GridImpl
     * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__NAME = eINSTANCE.getGrid_Name();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__LENGTH = eINSTANCE.getGrid_Length();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__WIDTH = eINSTANCE.getGrid_Width();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__CELLS = eINSTANCE.getGrid_Cells();

    /**
     * The meta object literal for the '{@link grid.gameoflife.gameOfLifeDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see grid.gameoflife.gameOfLifeDSL.impl.CellImpl
     * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__ROW = eINSTANCE.getCell_Row();

    /**
     * The meta object literal for the '<em><b>Col</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__COL = eINSTANCE.getCell_Col();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__STATE = eINSTANCE.getCell_State();

    /**
     * The meta object literal for the '{@link grid.gameoflife.gameOfLifeDSL.State <em>State</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see grid.gameoflife.gameOfLifeDSL.State
     * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getState()
     * @generated
     */
    EEnum STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '{@link grid.gameoflife.gameOfLifeDSL.Operator <em>Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see grid.gameoflife.gameOfLifeDSL.Operator
     * @see grid.gameoflife.gameOfLifeDSL.impl.GameOfLifeDSLPackageImpl#getOperator()
     * @generated
     */
    EEnum OPERATOR = eINSTANCE.getOperator();

  }

} //GameOfLifeDSLPackage
