/*
 * generated by Xtext 2.28.0
 */
package grid.gameoflife


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GameOfLifeDSLStandaloneSetup extends GameOfLifeDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GameOfLifeDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
