/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ui.tests;

import com.google.inject.Injector;
import gameoflife.grid.ui.internal.GridActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GameDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GridActivator.getInstance().getInjector("gameoflife.grid.GameDSL");
	}

}
