/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ui;

import com.google.inject.Injector;
import gameoflife.grid.ui.internal.GridActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GridActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GridActivator activator = GridActivator.getInstance();
		return activator != null ? activator.getInjector(GridActivator.GAMEOFLIFE_GRID_GAMEDSL) : null;
	}

}
