/*
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GameDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gameoflife/grid/parser/antlr/internal/InternalGameDSL.tokens");
	}
}
