/**
 * generated by Xtext 2.28.0
 */
package gameoflife.grid.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GameDSLUiModule extends AbstractGameDSLUiModule {
  public GameDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
